# Generated by Django 5.1 on 2024-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
