# Generated by Django 5.1 on 2024-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_identifier_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
