# Generated by Django 5.1 on 2024-09-11 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_identifier_icon'),
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
