# Generated by Django 5.1 on 2024-09-08 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table'),
        ),
        migrations.AddField(
            model_name='takeawayorder',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cashier'),
        ),
    ]
