# Generated by Django 5.1 on 2024-09-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeawayorder',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
