# Generated by Django 5.1 on 2024-09-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discount_orderitem_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commentary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commentary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
