# Generated by Django 5.1 on 2024-09-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_commentary_orderitem_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='status_closed',
            field=models.BooleanField(default=False),
        ),
    ]
