# Generated by Django 5.1 on 2024-09-09 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliveryorder_ready_tableorder_status_closed'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeawayorder',
            name='cashier',
        ),
        migrations.AddField(
            model_name='takeawayorder',
            name='branch_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branchstaff'),
        ),
    ]
