# Generated by Django 5.1 on 2024-09-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_extras'),
        ('products', '0007_category_identifier_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='products.productextra'),
        ),
    ]
