# Generated by Django 5.1 on 2024-09-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_branch'),
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.branch'),
            preserve_default=False,
        ),
    ]
