# Generated by Django 5.1 on 2024-09-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_takeawayorder_branch_staff_order_branch_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consumer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
