# Generated by Django 5.1 on 2024-09-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_branch_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='bookable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='position_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='position_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
