# Generated by Django 5.1 on 2024-10-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_bookable_table_position_x_table_position_y_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('number', 'branch'), name='unique_table_number_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('position_x', 'position_y', 'branch'), name='unique_table_position_per_branch'),
        ),
    ]
