# Generated by Django 5.1 on 2024-09-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/restaurants/banners/'),
        ),
    ]
