# Generated by Django 5.1 on 2024-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_table_unique_table_number_per_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
    ]
