# Generated by Django 5.1 on 2024-09-08 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_banner'),
        ('users', '0002_alter_employee_ended_at_alter_employee_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_all_employees', to='users.employee'),
        ),
    ]
