version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-2204:2024.05.1
    steps:
      - run:
          name: Deploy With SSH
          command: |
            ssh $USER@$IP "cd Tu-Resto && git pull && docker compose up -d --build"
workflows:
  deploy:
    jobs:
      - deploy:
        filters:
          branches:
            only: main

