# Generated by Django 5.1 on 2024-09-08 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_branch_employees'),
        ('users', '0002_alter_employee_ended_at_alter_employee_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_employees', to='restaurant.branch'),
            preserve_default=False,
        ),
    ]
