# Generated by Django 5.1 on 2024-09-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_branch_employees'),
        ('users', '0003_remove_employee_restaurant_employee_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_employees', to='restaurant.branch'),
        ),
    ]
