# Generated by Django 5.1 on 2024-09-08 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_branch_employees'),
        ('users', '0004_alter_employee_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_managers', to='restaurant.restaurant'),
        ),
    ]
